export const commentData = {
	sections: [
		{
			isRoot: true,
			isParent: true,
			title: "Metadata Information",
			fields: [
				{
					sectionName: "",
					isParent: false,
					isVisible: false,
					title: "Id",
					type: "text",
					name: "_id",
					fields: [],
				},
				{
					sectionName: "",
					isParent: false,
					isVisible: true,
					title: "Name",
					type: "text",
					name: "name",
					fields: [],
				},
			],
		},
		{
			isRoot: true,
			isParent: true,
			title: "Input",
			name: "input",
			type: "section",
			fields: [
				{
					sectionName: "input",
					isParent: false,
					isVisible: false,
					title: "Data",
					type: "section",
					name: "data",
					fields: [
						{
							sectionName: "input.data",
							isParent: false,
							isVisible: true,
							title: "Table Type",
							type: "text",
							name: "table_type",
							fields: [],
						},
						{
							sectionName: "input.data",
							isParent: false,
							isVisible: true,
							title: "Table",
							type: "text",
							name: "table",
							fields: [],
						},
						{
							sectionName: "input.data.context",
							isParent: false,
							isVisible: true,
							title: "Context",
							type: "section",
							name: "context",
							fields: [],
						},
					],
				},
				{
					isParent: false,
					isVisible: true,
					title: "Artifact",
					type: "section",
					name: "artifact",
					fields: [
						{
							sectionName: "input.artifact",
							isParent: false,
							isVisible: true,
							title: "Flavour",
							type: "text",
							name: "flavour",
							fields: [],
						},
						{
							sectionName: "input.artifact",
							isParent: false,
							isVisible: true,
							title: "Path",
							type: "text",
							name: "path",
							fields: [],
						},
					],
				},
			],
		},
		{
			isRoot: true,
			isParent: true,
			title: "Metadata Information",
			fields: [],
		},
		{
			isRoot: true,
			isParent: true,
			title: "Metadata Information",
			fields: [],
		},
		{
			isRoot: true,
			isParent: true,
			title: "Metadata Information",
			fields: [],
		},
		{
			isRoot: true,
			isParent: true,
			title: "Metadata Information",
			fields: [],
		},
		{
			isRoot: true,
			isParent: true,
			title: "Metadata Information",
			fields: [],
		},
		{
			isRoot: true,
			isParent: true,
			title: "Metadata Information",
			fields: [],
		},

		{
			isRoot: true,
			isParent: true,
			title: "Metadata Information",
			fields: [],
		},
	],
};
